### ISSUE TITLE
Problem with SEB on WindowsMachine

### ISSUE THREAD

**Issue by dkummer63** [SafeExamBrowser/seb-win-refactoring#721]
Hello and thank you for your excellent work. I have one Student with a
Lenovo, Win 11, updatet,
He can not start an exam. 
There is the following Errors: 
[2023-06-08_10h40m16s_Browser.log](https://github.com/SafeExamBrowser/seb-win-refactoring/files/13449535/2023-06-08_10h40m16s_Browser.log)
![image001](https://github.com/SafeExamBrowser/seb-win-refactoring/assets/89595743/220318c2-7145-4919-9cb9-34b568aa6997)
![image002](https://github.com/SafeExamBrowser/seb-win-refactoring/assets/89595743/062753c5-9831-4e11-a973-76d5a197145d)
![image003](https://github.com/SafeExamBrowser/seb-win-refactoring/assets/89595743/b656f463-588b-4dae-8cd8-5a22414320a6)

Thanks for any help
Daniel

**Comment by dbuechel** [comment]
I'd need the runtime log file of the affected session in order to determine what exactly went wrong here.

**Comment by dkummer63** [comment]
It took me some time to get the imformation from the student. Thanks for any help.
[2023-12-06_10h16m35s_Runtime.log](https://github.com/SafeExamBrowser/seb-win-refactoring/files/13581538/2023-12-06_10h16m35s_R
[safeexan.zip](https://github.com/SafeExamBrowser/seb-win-refactoring/files/13581552/safeexan.zip)
untime.log)

**Comment by dkummer63** [comment]
[2023-12-06_10h16m35s_Runtime.log](https://github.com/SafeExamBrowser/seb-win-refactoring/files/13581563/2023-12-06_10h16m35s_Runtime.log)

**Comment by dbuechel** [comment]
It looks like that student has a local client configuration which is (or was) encrypted with a certificate, and the certificate cannot be found on the system:

```
2023-12-06 10:16:41.762 [08] - DEBUG: [BinaryParser] Attempting to parse public key hash block with prefix 'phsk'...
2023-12-06 10:16:41.763 [08] - DEBUG: [PublicKeySymmetricEncryption] Parsing public key hash...
2023-12-06 10:16:41.778 [08] - DEBUG: [PublicKeySymmetricEncryption] Parsing symmetric key...
2023-12-06 10:16:41.844 [08] - ERROR: [ConfigurationRepository] Unexpected error while trying to load 'file:///C:/Users/yantr/AppData/Roaming/SafeExamBrowser/SebClientSettings.seb'!

   Exception Message: Ungültigen Anbietertyp angegeben

   Exception Type: System.Security.Cryptography.CryptographicException
```

If the local client configuration shouldn't be there or isn't required for the exam, then simply deleting it should resolve the issue.

**Comment by dbuechel** [comment]
Any updates on this?

**Comment by dkummer63** [comment]
Finally, there is new information: The status is still the same. He deleted all files and reinstalled the programm. Still: 
![grafik](https://github.com/SafeExamBrowser/seb-win-refactoring/assets/89595743/d56c9f9e-bab2-4288-b7c9-7b872d341677)
Maybe the logfile might help: 
[2024-02-19_22h59m03s_Runtime.log](https://github.com/SafeExamBrowser/seb-win-refactoring/files/14340599/2024-02-19_22h59m03s_Runtime.log)

**Comment by dbuechel** [comment]
Unfortunately, it still appears to be the exact same issue. Here the complete excerpt form the runtime application log:

```
2024-02-19 22:59:12.293 [04] - INFO: Initializing application configuration...
2024-02-19 22:59:12.298 [04] - INFO: Found configuration file in app data directory: 'file:///C:/Users/yantr/AppData/Roaming/SafeExamBrowser/SebClientSettings.seb'.
2024-02-19 22:59:12.348 [04] - INFO: [ConfigurationRepository] Initialized default settings, now attempting to load 'file:///C:/Users/yantr/AppData/Roaming/SafeExamBrowser/SebClientSettings.seb'...
2024-02-19 22:59:12.365 [04] - DEBUG: [FileResourceLoader] Can load 'file:///C:/Users/yantr/AppData/Roaming/SafeExamBrowser/SebClientSettings.seb' as it is an existing file.
2024-02-19 22:59:12.365 [04] - DEBUG: [FileResourceLoader] Loading data from 'file:///C:/Users/yantr/AppData/Roaming/SafeExamBrowser/SebClientSettings.seb'...
2024-02-19 22:59:12.379 [04] - DEBUG: [FileResourceLoader] Created 'System.IO.FileStream' for 3.589 KB data in 'file:///C:/Users/yantr/AppData/Roaming/SafeExamBrowser/SebClientSettings.seb'.
2024-02-19 22:59:12.379 [04] - INFO: [ConfigurationRepository] Tried to load data from 'file:///C:/Users/yantr/AppData/Roaming/SafeExamBrowser/SebClientSettings.seb' using FileResourceLoader -> Result: Success.
2024-02-19 22:59:12.395 [04] - DEBUG: [BinaryParser] 'System.IO.FileStream' starting with 'phsk' matches the Binary format.
2024-02-19 22:59:12.395 [04] - DEBUG: [GZipCompressor] Starting decompression of 'System.IO.FileStream' with 3.589 KB data...
2024-02-19 22:59:12.395 [04] - DEBUG: [GZipCompressor] Successfully decompressed 3.589 KB to 3.566 KB data.
2024-02-19 22:59:12.395 [04] - DEBUG: [BinaryParser] Attempting to parse public key hash block with prefix 'phsk'...
2024-02-19 22:59:12.395 [04] - DEBUG: [PublicKeySymmetricEncryption] Parsing public key hash...
2024-02-19 22:59:12.428 [04] - DEBUG: [PublicKeySymmetricEncryption] Parsing symmetric key...
2024-02-19 22:59:12.507 [04] - ERROR: [ConfigurationRepository] Unexpected error while trying to load 'file:///C:/Users/yantr/AppData/Roaming/SafeExamBrowser/SebClientSettings.seb'!

   Exception Message: Ungültigen Anbietertyp angegeben

   Exception Type: System.Security.Cryptography.CryptographicException

   bei System.Security.Cryptography.Utils.CreateProvHandle(CspParameters parameters, Boolean randomKeyContainer)
   bei System.Security.Cryptography.Utils.GetKeyPairHelper(CspAlgorithmType keyType, CspParameters parameters, Boolean randomKeyContainer, Int32 dwKeySize, SafeProvHandle& safeProvHandle, SafeKeyHandle& safeKeyHandle)
   bei System.Security.Cryptography.RSACryptoServiceProvider.GetKeyPair()
   bei System.Security.Cryptography.RSACryptoServiceProvider..ctor(Int32 dwKeySize, CspParameters parameters, Boolean useDefaultKeySize)
   bei System.Security.Cryptography.X509Certificates.X509Certificate2.get_PrivateKey()
   bei SafeExamBrowser.Configuration.Cryptography.PublicKeyEncryption.Decrypt(Stream data, Int64 offset, X509Certificate2 certificate) in C:\Users\appveyor\projects\seb-win-refactoring-phv3mbelx16fm9ou\SafeExamBrowser.Configuration\Cryptography\PublicKeyEncryption.cs:Zeile 89.
   bei SafeExamBrowser.Configuration.Cryptography.PublicKeySymmetricEncryption.ParseSymmetricKey(Stream data, X509Certificate2 certificate) in C:\Users\appveyor\projects\seb-win-refactoring-phv3mbelx16fm9ou\SafeExamBrowser.Configuration\Cryptography\PublicKeySymmetricEncryption.cs:Zeile 101.
   bei SafeExamBrowser.Configuration.Cryptography.PublicKeySymmetricEncryption.Decrypt(Stream data, Stream& decryptedData, X509Certificate2& certificate) in C:\Users\appveyor\projects\seb-win-refactoring-phv3mbelx16fm9ou\SafeExamBrowser.Configuration\Cryptography\PublicKeySymmetricEncryption.cs:Zeile 43.
   bei SafeExamBrowser.Configuration.DataFormats.BinaryParser.ParsePublicKeyBlock(Stream data, String prefix, PasswordParameters password) in C:\Users\appveyor\projects\seb-win-refactoring-phv3mbelx16fm9ou\SafeExamBrowser.Configuration\DataFormats\BinaryParser.cs:Zeile 153.
   bei SafeExamBrowser.Configuration.DataFormats.BinaryParser.TryParse(Stream data, PasswordParameters password) in C:\Users\appveyor\projects\seb-win-refactoring-phv3mbelx16fm9ou\SafeExamBrowser.Configuration\DataFormats\BinaryParser.cs:Zeile 100.
   bei SafeExamBrowser.Configuration.ConfigurationRepository.TryParseData(Stream data, EncryptionParameters& encryption, FormatType& format, IDictionary`2& rawData, PasswordParameters password) in C:\Users\appveyor\projects\seb-win-refactoring-phv3mbelx16fm9ou\SafeExamBrowser.Configuration\ConfigurationRepository.cs:Zeile 198.
   bei SafeExamBrowser.Configuration.ConfigurationRepository.TryLoadSettings(Uri resource, AppSettings& settings, PasswordParameters password) in C:\Users\appveyor\projects\seb-win-refactoring-phv3mbelx16fm9ou\SafeExamBrowser.Configuration\ConfigurationRepository.cs:Zeile 134.

2024-02-19 22:59:30.698 [04] - WARNING: The configuration has failed!
```

In short: This user has a client configuration under `C:/Users/yantr/AppData/Roaming/SafeExamBrowser/SebClientSettings.seb` which is encrypted with a certificate (that is not available on the user's machine) and thus SEB cannot decrypt and load the configuration, thus the session initialization fails.

**Comment by dkummer63** [comment]
I saw the student today and deleted the SebClientSettings and all works well. Sorry, it was almost too easy. Thank you for your support and all well!

**Comment by dbuechel** [comment]
Excellent, happy to hear that it works now.

**Comment by dkummer63** [comment]
Guten Tag Herr Büchel
Ich kann im Moment auf github keinen Eintrag machen. Wir haben an unserer Schule einen Betrugsversuch und ich müsste das Verification-Tool herunterladen, aber das ist über safeexambrowser im moment nicht erreichbar.
Freundliche Grüsse
Daniel Kummer

**Comment by dbuechel** [comment]
Die neuste Version kann unter folgenden URLs heruntergeladen werden:

https://github.com/SafeExamBrowser/seb-win-verificator/releases/download/v1.0.2/Verificator_1.0.2.29.zip
https://sebdev.ethz.ch/api/buildjobs/ideeyfqndrawm3ip/artifacts/Verificator/bin/Verificator_1.0.2.50.zip

**Comment by dkummer63** [comment]
Danke für die rasche Antwort. Der erste Link funktioniert aber leider nicht.
Kann man für ein Mac-Gerät auch etwas machen?

**Comment by dbuechel** [comment]
Stimmt, das ist ein veralteter Link auf der Webseite, das müssen wir noch aktualisieren. Hier der korrekte Link:

https://github.com/SafeExamBrowser/seb-win-verificator/releases/download/v1.0.2/Verificator_1.0.2.31.zip

Für macOS gibt es ebenfalls einen Verifikator, siehe https://github.com/SafeExamBrowser/seb-mac-verificator/releases.

**Comment by dkummer63** [comment]
Perfekt! Danke und schöner Tag noch
