### ISSUE TITLE
Caught unexpected exception while performing operation 'LazyInitializationOperation'!

### ISSUE THREAD

**Issue by adixy94** [SafeExamBrowser/seb-win-refactoring#882]
**Describe the Bug**
A student gets the "SEB failed to start a new session!" error when they try to start the exam. The student is advised to install the latest version of C++ redistributable, reinstall the SEB, and reboot the computer. However, the same issue appears when they try to start the exam. The SEB is installed using the .exe file.

**Version Information**
 - OS: Windows 11, Microsoft Windows NT 10.0.26120.0 (x64)
 - Computer: 'LAPTOP-576N8CNP' is a ThinkPad P1 Gen 4i 20Y3004DUS manufactured by LENOVO
 - Safe Exam Browser: Safe Exam Browser, Version 3.6.0 (x64), Build 3.6.0.633

**Screenshots**
[Screenshot of the installed C++ redistributables](https://prnt.sc/1QwD5Pj2tFNZ)
**Error from the log**

ERROR: Caught unexpected exception while performing operation 'LazyInitializationOperation'!

   Exception Message: Access is denied
   Exception Type: System.ComponentModel.Win32Exception

   at SimpleWifi.Win32.WlanClient..ctor()
   at SimpleWifi.Wifi..ctor()
   at SafeExamBrowser.SystemComponents.Network.NetworkAdapter.Initialize() in C:\Users\appveyor\projects\seb-win-refactoring-phv3mbelx16fm9ou\SafeExamBrowser.SystemComponents\Network\NetworkAdapter.cs:line 92
   at SafeExamBrowser.Client.Operations.ShellOperation.InitializeSystemComponents() in C:\Users\appveyor\projects\seb-win-refactoring-phv3mbelx16fm9ou\SafeExamBrowser.Client\Operations\ShellOperation.cs:line 214
   at SafeExamBrowser.Client.Operations.ShellOperation.Perform() in C:\Users\appveyor\projects\seb-win-refactoring-phv3mbelx16fm9ou\SafeExamBrowser.Client\Operations\ShellOperation.cs:line 81
   at SafeExamBrowser.Core.OperationModel.OperationSequence.Perform() in C:\Users\appveyor\projects\seb-win-refactoring-phv3mbelx16fm9ou\SafeExamBrowser.Core\OperationModel\OperationSequence.cs:line 108

**SEB log files**
1.  Client - [2024-05-08_15h09m38s_Client.log](https://github.com/SafeExamBrowser/seb-win-refactoring/files/15336181/2024-05-08_15h09m38s_Client.log)
2. Runtime - [2024-05-08_15h09m38s_Runtime.log](https://github.com/SafeExamBrowser/seb-win-refactoring/files/15336182/2024-05-08_15h09m38s_Runtime.log)

**Comment by dbuechel** [comment]
This most likely is a (configuration) issue on the system of the student. It appears that access to the WiFi control is denied. This may be caused by a corrupted WMI repository, a registry manipulation resp. group policy and can likely only be resolved by a support specialist or the student themselves by fixing their system (configuration).

**Comment by abdadhim** [comment]
> Ensure that you have given SEB permission to access the location services (see Settings > Privacy & security > Location in the system control panel of Windows).

This works! Thank you so much!

**Comment by mogli73** [comment]
Location Services??

My clients don't have admin. rights. So how can they activate these settings?

And why on some laptops it works without these location services?

**Comment by mogli73** [comment]
good day!

I have installed it with MEPM (Intune) on several virtual machines. None of them have local admin rights, and the location service on these is off. SEB works. However, I still can't understand why it doesn't work on several student machines.

I will check the location settings on the affected machines.

**Comment by afifudinmtop** [comment]
> Ensure that you have given SEB permission to access the location services (see Settings > Privacy & security > Location in the system control panel of Windows).

thanks bro
